app-template:
  controllers:
    main:
      pod:
        annotations:
          operator.1password.io/item-path: "vaults/4uaua4a45yuhnwhehp5bwylmti/items/2ortihqm434zoylzxr5pag7bba"
          operator.1password.io/item-name: "secrets"
      containers:
        main:
          image:
            repository: lscr.io/linuxserver/obsidian
            tag: latest
            pullPolicy: Always
          env:
            TZ: America/Chicago
            PUID: "99"
            PGID: "100"
            DOCKER_MODS: linuxserver/mods:universal-git
            DASHBOARD: selkies-dashboard
            CUSTOM_USER:
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: custom-user
            PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: password
          # ports:
          #   - name: http
          #     containerPort: 3000
          #   - name: https
          #     containerPort: 3001
  service:
    main:
      controller: main
      ports:
        http:
          port: 3000
          targetPort: http
        https:
          port: 3001
          targetPort: https
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: homelab-tunnel.eaglepass.io
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host obsidian.eaglepass.io
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - secretName: obsidian-tls
          hosts:
            - *host
  # persistence:
  #   data:
  #     enabled: true
  #     type: nfs
  #     server: 10.0.50.3
  #     path: /mnt/user/obsidian
  #     advancedMounts:
  #       main:
  #         main:
  #           - path: /config
  #   vaults:
  #     enabled: true
  #     type: nfs
  #     server: 10.0.50.3
  #     path: /mnt/user/obsidian
  #     advancedMounts:
  #       main:
  #         main:
  #           - path: /vaults